### ISSUE TITLE
Career History -- Background -- Still Blue

### ISSUE THREAD

**Issue by aecyia** [aecyia/Sakura#3]
+ original blue !
+ make pink !

![1](https://user-images.githubusercontent.com/57078659/211209264-084d9154-40cc-44d8-af66-434140ad291a.png)

**Comment by VMPYRC** [comment]
original for reference:

![2024_October_01_Tuesday_09_31_29_902_PM](https://github.com/user-attachments/assets/6fd9fa8a-7c11-4159-8598-bac11d892fc8)

**Comment by VMPYRC** [comment]
This probably has to do with the LAYOUT files:

- HUDCareerPanelHistoryEntry
- HUDCareerPanel
- HUDDegreeHistoryEntry
