### ISSUE TITLE
Plumbot Needs -- Background -- Still Blue

### ISSUE THREAD

**Issue by aecyia** [aecyia/Sakura#8]
+ Background is blue
+ Make pink :3
+ Occult / Species -- Plumbot
+ Needs Tab

![2023-01-08_05-35-50-951-PM](https://user-images.githubusercontent.com/57078659/211222591-bfa64649-cda4-4c36-8420-f3bbaca1ae21.png)

**Comment by aecyia** [comment]
With no Trait Chips installed

![image](https://user-images.githubusercontent.com/57078659/219908109-936c7190-9bcb-49c9-adae-2a28bb673b2c.png)

**Comment by VMPYRC** [comment]
original for reference:

![2024_October_01_Tuesday_09_31_58_668_PM](https://github.com/user-attachments/assets/489687aa-0691-4b02-9845-0cb2ce8b2819)

**Comment by VMPYRC** [comment]
![2024_October_05_Saturday_06_44_53_973_PM](https://github.com/user-attachments/assets/cb0e18f0-825f-42cb-be28-f7b5a2ea8bdb)

fixed for v0.0.9
